version: '3'

volumes:
 postgres_data:
  driver: local

networks:
  microservice-net:
    external: false

services:
  serviceweb_db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_DB: myname_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - microservice-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
      
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123456!"
    ports:
      - "16543:80"
    depends_on:
      - serviceweb_db
    networks:
      - microservice-net
